### ISSUE TITLE
Issue : Clean install rbpi2 

### ISSUE THREAD

**Issue by vi353** [baliscope/periapi#10]
Some months ago, my raspberry pi2 was running "periapi" without problems, Now I decides format my sd and install all again. Running Python 3.4, this is the output of periapi:

$ python 
Python 3.4.2 (default, Oct  8 2014, 14:38:51) 
[GCC 4.9.1] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> 
$ periapi   
Traceback (most recent call last):
  File "/usr/local/bin/periapi", line 9, in <module>
    load_entry_point('periapi==0.7.9', 'console_scripts', 'periapi')()
  File "/usr/lib/python3/dist-packages/pkg_resources.py", line 356, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "/usr/lib/python3/dist-packages/pkg_resources.py", line 2476, in load_entry_point
    return ep.load()
  File "/usr/lib/python3/dist-packages/pkg_resources.py", line 2190, in load
    ['__name__'])
  File "/usr/local/lib/python3.4/dist-packages/periapi/__init__.py", line 7, in <module>
    from .api import PeriAPI
  File "/usr/local/lib/python3.4/dist-packages/periapi/api.py", line 8, in <module>
    from .login import LoginSession
  File "/usr/local/lib/python3.4/dist-packages/periapi/login.py", line 14, in <module>
    from path import path
ImportError: cannot import name 'path'

Help me, please.

**Comment by mrplow** [comment]
path 10 breaks it, you'll need to downgrade
pip3 install -I path.py==9.1
