### ISSUE TITLE
no work

### ISSUE THREAD

**Issue by TuxNuX** [baliscope/periapi#13]
install with pip3 on linux (python 3.4)
```
$ periapi
Traceback (most recent call last):
  File "/usr/bin/periapi", line 11, in <module>
    load_entry_point('periapi==0.7.9', 'console_scripts', 'periapi')()
  File "/usr/lib/python3.4/site-packages/pkg_resources/__init__.py", line 560, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "/usr/lib/python3.4/site-packages/pkg_resources/__init__.py", line 2648, in load_entry_point
    return ep.load()
  File "/usr/lib/python3.4/site-packages/pkg_resources/__init__.py", line 2302, in load
    return self.resolve()
  File "/usr/lib/python3.4/site-packages/pkg_resources/__init__.py", line 2308, in resolve
    module = __import__(self.module_name, fromlist=['__name__'], level=0)
  File "/usr/lib/python3.4/site-packages/periapi/__init__.py", line 7, in <module>
    from .api import PeriAPI
  File "/usr/lib/python3.4/site-packages/periapi/api.py", line 8, in <module>
    from .login import LoginSession
  File "/usr/lib/python3.4/site-packages/periapi/login.py", line 14, in <module>
    from path import path
ImportError: cannot import name 'path'
```

**Comment by mrplow** [comment]
path 10 breaks it, you'll need to downgrade
pip3 install -I path.py==9.1
