### ISSUE TITLE
cannot import name 'path'

### ISSUE THREAD

**Issue by Mebrahem1** [baliscope/periapi#16]
```
macs-MacBook-Pro:~ mac$ periapi 
Traceback (most recent call last):
  File "/usr/local/bin/periapi", line 7, in <module>
    from periapi.__main__ import run
  File "/usr/local/lib/python3.6/site-packages/periapi/__init__.py", line 7, in <module>
    from .api import PeriAPI
  File "/usr/local/lib/python3.6/site-packages/periapi/api.py", line 8, in <module>
    from .login import LoginSession
  File "/usr/local/lib/python3.6/site-packages/periapi/login.py", line 14, in <module>
    from path import path
ImportError: cannot import name 'path'
```

How can fix it?

**Comment by ricardotenv** [comment]
Comment or edit the archive __ init __.py"
