### ISSUE TITLE
Crash when logging in

### ISSUE THREAD

**Issue by YoelPLG** [baliscope/periapi#6]
Hello again man.
Today I was trying to use periapi with another twitter account, but for some reason when I put the PIN code, it crashes:
Please enter the PIN: XXXXXXX
Traceback (most recent call last):
  File "/usr/local/bin/periapi", line 9, in <module>
    load_entry_point('periapi==0.7.8', 'console_scripts', 'periapi')()
  File "/usr/local/lib/python3.4/dist-packages/periapi/**main**.py", line 25, in run
    BadCLI()
  File "/usr/local/lib/python3.4/dist-packages/periapi/**main**.py", line 49, in **init**
    self.api = PeriAPI()
  File "/usr/local/lib/python3.4/dist-packages/periapi/api.py", line 33, in **init**
    self.session = LoginSession()
  File "/usr/local/lib/python3.4/dist-packages/periapi/login.py", line 80, in **init**
    cookie = self.authenticate()
  File "/usr/local/lib/python3.4/dist-packages/periapi/login.py", line 197, in authenticate
    if len(resp.json().get("errors")) > 0:
TypeError: object of type 'NoneType' has no len()

What am I doing wrong? Thanks in advance!

**Comment by YoelPLG** [comment]
Solution: I logged in using the periscope app, and then here. (It was a new account) Now it's working!

**Comment by baliscope** [comment]
To confirm, this worked the first time, right? Only when putting in the new account you had this issue?

**Comment by Copelaw** [comment]
Same problem for me. There is another solution?
